#!/usr/bin/env python3
"""
Generate realistic sample telemetry for Cyber-EW Fusion Cell.

Outputs JSON events and plain-text logs under data/inputs/sample_generated by
default. The generated data is defensive test telemetry only.
"""
import argparse
import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path


USERS = ["alice", "bob", "charlie", "svc_backup", "admin"]
INTERNAL_IPS = [f"192.168.1.{i}" for i in range(20, 80)]
SERVERS = ["192.168.10.10", "192.168.10.20", "192.168.20.15"]
EXTERNAL_IPS = ["8.8.8.8", "1.1.1.1", "203.0.113.50", "198.51.100.23"]


def utc_iso(dt):
    return dt.astimezone(timezone.utc).isoformat()


def normal_network_event(ts):
    return {
        "timestamp": utc_iso(ts),
        "source_ip": random.choice(INTERNAL_IPS),
        "destination_ip": random.choice(EXTERNAL_IPS + SERVERS),
        "destination_port": random.choice([53, 80, 123, 443]),
        "protocol": random.choice(["TCP", "UDP"]),
        "event_type": "network_connection",
        "severity": "info",
        "bytes_sent": random.randint(120, 4000),
        "bytes_received": random.randint(200, 20000),
        "details": {"success": True, "service": random.choice(["dns", "web", "ntp"])}
    }


def failed_login(ts, source_ip=None, username=None, attempts=1):
    return {
        "timestamp": utc_iso(ts),
        "source_ip": source_ip or random.choice(INTERNAL_IPS),
        "username": username or random.choice(USERS),
        "event_type": "authentication",
        "severity": "high",
        "details": {
            "success": False,
            "reason": "invalid_password",
            "attempts": attempts
        }
    }


def smb_lateral_movement(ts, source_ip):
    return {
        "timestamp": utc_iso(ts),
        "source_ip": source_ip,
        "destination_ip": random.choice(SERVERS),
        "destination_port": 445,
        "protocol": "TCP",
        "event_type": "network_connection",
        "severity": "high",
        "details": {"success": False, "message": "SMB connection refused"}
    }


def c2_beacon(ts, source_ip):
    return {
        "timestamp": utc_iso(ts),
        "source_ip": source_ip,
        "destination_ip": "203.0.113.50",
        "destination_port": 443,
        "protocol": "TCP",
        "event_type": "network_connection",
        "severity": "medium",
        "bytes_sent": random.randint(200, 1200),
        "bytes_received": random.randint(800, 5000),
        "details": {"interval": "periodic", "repeat_count": 5, "message": "beacon-like callback"}
    }


def ransomware_file_event(ts, host_ip):
    extension = random.choice([".encrypted", ".locked", ".crypt"])
    return {
        "timestamp": utc_iso(ts),
        "source_ip": host_ip,
        "event_type": "file_access",
        "severity": "critical",
        "file_path": f"C:/Users/Public/document_{random.randint(1, 500)}.docx{extension}",
        "details": {"operation": "encrypt", "message": "bulk file rename detected"}
    }


def data_staging_event(ts, host_ip):
    return {
        "timestamp": utc_iso(ts),
        "source_ip": host_ip,
        "username": random.choice(["admin", "svc_backup"]),
        "event_type": "process_creation",
        "severity": "medium",
        "process_name": random.choice(["7z.exe", "powershell.exe", "tar.exe"]),
        "details": {
            "command": "7z.exe a C:/Temp/archive.7z C:/Sensitive/*",
            "message": "archive creation before outbound transfer"
        }
    }


def generate_events(count, seed):
    random.seed(seed)
    start = datetime.now(timezone.utc) - timedelta(hours=2)
    events = []

    for i in range(count):
        events.append(normal_network_event(start + timedelta(seconds=i * 15)))

    attacker_ip = "192.168.1.66"
    for i in range(14):
        events.append(failed_login(start + timedelta(minutes=20, seconds=i * 8), attacker_ip, "admin", i + 1))

    for i in range(8):
        events.append(smb_lateral_movement(start + timedelta(minutes=35, seconds=i * 20), attacker_ip))

    for i in range(6):
        events.append(c2_beacon(start + timedelta(minutes=55, seconds=i * 60), "192.168.1.42"))

    for i in range(24):
        events.append(ransomware_file_event(start + timedelta(minutes=75, seconds=i * 5), "192.168.1.55"))

    events.append(data_staging_event(start + timedelta(minutes=90), "192.168.1.55"))
    events.sort(key=lambda item: item["timestamp"])
    return events


def write_syslog(events, output_path):
    with open(output_path, "w", encoding="utf-8") as f:
        for event in events:
            source_ip = event.get("source_ip", "-")
            event_type = event.get("event_type", "system_alert")
            severity = event.get("severity", "info").upper()
            message = event.get("details", {}).get("message", event_type)
            f.write(f"{event['timestamp']} {severity} src={source_ip} type={event_type} {message}\n")


def main():
    parser = argparse.ArgumentParser(description="Generate Cyber-EW sample telemetry")
    parser.add_argument("--count", type=int, default=100, help="Number of normal baseline events")
    parser.add_argument("--seed", type=int, default=1337, help="Random seed for repeatable output")
    parser.add_argument("--output-dir", default="data/inputs/sample_generated", help="Output directory")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    events = generate_events(args.count, args.seed)

    json_path = output_dir / "sample_events.json"
    log_path = output_dir / "sample_syslog.log"

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(events, f, indent=2)

    write_syslog(events, log_path)

    print(f"Generated {len(events)} events")
    print(f"JSON: {json_path}")
    print(f"Syslog: {log_path}")


if __name__ == "__main__":
    main()
